[project]
name = 'python-app-template'
description = 'Boilerplate for Python applications'
license = {text = 'MIT License'}
readme = 'README.md'
requires-python = '>=3.10'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
]
dynamic = ['version']

dependencies = [
    'toml'
]

[project.optional-dependencies]
dev = [
    'coverage',
    'freezegun',
    'mypy',
    'pip-tools',
    'pre-commit',
    'pytest',
    'ruff',
]

[project.entry-points.'console_scripts']
pythonapp = 'pythonapp.app:main'

[build-system]
# Minimum requirements for the build system to execute.
requires = ['setuptools', 'wheel']

[tools.setuptools]
packages = ['pythonapp']

[tool.pythonapp]
# to write json-formatted logs to disk, uncomment the following line specify the file location
# log_file = '/Users/you/logs/pythonapp.log'

[tool.ruff]
line-length = 120
extend-select = ['I']

[tool.ruff.format]
quote-style = 'single'

[tool.setuptools.dynamic]
version = {attr = 'pythonapp.__version__'}