[project]
name = 'python-app-template'
description = 'Boilerplate for Python applications'
license = {text = 'MIT License'}
readme = 'README.md'
requires-python = '>=3.10'
classifiers = [
    'Programming Language :: Python :: 3',
    'License :: OSI Approved :: MIT License',
]
dynamic = ['version']

dependencies = [
]

[project.optional-dependencies]
dev = [
    'mypy',
    'pip-tools',
    'pre-commit',
    'pytest',
    'ruff',
]

[tools.setuptools]
packages = ['pythonapp']

[build-system]
# Minimum requirements for the build system to execute.
requires = ['setuptools', 'wheel']  # PEP 508 specifications.

[tool.ruff]
line-length = 120
extend-select = ['I']

[tool.ruff.format]
quote-style = 'single'

[tool.setuptools.dynamic]
version = {attr = 'pythonapp.__version__'}