name: run-code-checks
run-name: ${{ github.action }} triggered by ${{ github.event_name }} from ${{ github.actor }}
on: [push]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
            cache: true
      - name: Install dependencies
        run: pdm install
      - name: lint
        run: |
           ruff . --fix
           ruff format .
      - name: type check
        run: |
           mypy .
      - name: run tests
        run: |
           pytest

